// <auto-generated />
using System;
using Inventory.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventory.Server.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260224151920_AddDesignationEntity")]
    partial class AddDesignationEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inventory.Server.Models.AccountHead", b =>
                {
                    b.Property<int>("AccountCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountCode"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AccountType")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Address1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Address2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Address3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Address4")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CSTNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CollAgentID")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DueDays")
                        .HasColumnType("int");

                    b.Property<int?>("EmpId")
                        .HasColumnType("int");

                    b.Property<int?>("FormID")
                        .HasColumnType("int");

                    b.Property<int?>("GoodsType")
                        .HasColumnType("int");

                    b.Property<int>("GroupUnder")
                        .HasColumnType("int");

                    b.Property<string>("MobileNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PartyType")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pincode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PurchaseSalesTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("RateType")
                        .HasColumnType("int");

                    b.Property<int?>("RouteID")
                        .HasColumnType("int");

                    b.Property<string>("TIN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UserDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("AccountCode");

                    b.ToTable("AccountHead");
                });

            modelBuilder.Entity("Inventory.Server.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<int>("CategoryGroupId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryGroupId");

                    b.ToTable("Category", "Reference");
                });

            modelBuilder.Entity("Inventory.Server.Models.CategoryGroup", b =>
                {
                    b.Property<int>("CategoryGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryGroupId"));

                    b.Property<string>("CategoryGroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryGroupId");

                    b.ToTable("CategoryGroup", "Reference");
                });

            modelBuilder.Entity("Inventory.Server.Models.Core.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("AccountId");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("Inventory.Server.Models.Core.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BrandId");

                    b.ToTable("Brand", "Reference");
                });

            modelBuilder.Entity("Inventory.Server.Models.Core.Designation", b =>
                {
                    b.Property<int>("DesignationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DesignationId"));

                    b.Property<string>("DesignationName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("FinancialYearId")
                        .HasColumnType("int");

                    b.HasKey("DesignationId");

                    b.ToTable("Designation", "Reference");
                });

            modelBuilder.Entity("Inventory.Server.Models.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpId"));

                    b.Property<string>("Address1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Address2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Address3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int?>("Counter")
                        .HasColumnType("int");

                    b.Property<double?>("DA")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DesignationId")
                        .HasColumnType("int");

                    b.Property<string>("EmailId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmpCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GuardianName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsPermanent")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSalesman")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PinCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Reason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("RemovalDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Salary")
                        .HasColumnType("float");

                    b.Property<int?>("UnderNameId")
                        .HasColumnType("int");

                    b.HasKey("EmpId");

                    b.HasIndex("DesignationId");

                    b.ToTable("EMPLOYEEMASTER", "dbo");
                });

            modelBuilder.Entity("Inventory.Server.Models.Godown", b =>
                {
                    b.Property<int>("GodownID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GodownID"));

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("GodownName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Insurance")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("InsuranceFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InsuranceTo")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsGodown")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Make")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("TaxFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TaxTo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UserDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("VanRegNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GodownID");

                    b.ToTable("Godown", "Reference");
                });

            modelBuilder.Entity("Inventory.Server.Models.InventoryTransaction", b =>
                {
                    b.Property<int>("TempId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TempId"));

                    b.Property<decimal?>("AdjGrossAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BatchNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BatchNo1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BatchNo2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BatchNo3")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BillCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("BillFreeQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BillQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BillRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CancelDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CancelFlag")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Cess")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("DefectiveFlag")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscountAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ExciseDuty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ExciseDutyAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FinancialYearID")
                        .HasColumnType("int");

                    b.Property<decimal?>("FreeMultiplier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FreeQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("FreeUnitId")
                        .HasColumnType("int");

                    b.Property<int?>("GodownID")
                        .HasColumnType("int");

                    b.Property<decimal?>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GrossAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("InventoryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InventoryNo")
                        .HasColumnType("int");

                    b.Property<string>("InventoryType")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int?>("ItemID")
                        .HasColumnType("int");

                    b.Property<decimal?>("MRP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Mode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("ModelID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Multiplier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Narration")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("OtherPur")
                        .HasColumnType("float");

                    b.Property<int?>("PurchaseNo")
                        .HasColumnType("int");

                    b.Property<decimal?>("PurchaseRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Quantity1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Quantity2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Quantity3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReturnType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("RoundOff")
                        .HasColumnType("float");

                    b.Property<decimal?>("SalesRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("SalesmanGodownFlag")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Services")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Shortage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SlNo")
                        .HasColumnType("int");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TaxableHead")
                        .HasColumnType("int");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("TransType")
                        .HasColumnType("bit");

                    b.Property<int?>("UnitID")
                        .HasColumnType("int");

                    b.Property<bool?>("isEstimate")
                        .HasColumnType("bit");

                    b.HasKey("TempId");

                    b.ToTable("InventoryTransactions");
                });

            modelBuilder.Entity("Inventory.Server.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int?>("CSTPurchaseTaxHead")
                        .HasColumnType("int");

                    b.Property<double?>("CSTPurchaseTaxRate")
                        .HasColumnType("float");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryType")
                        .HasColumnType("int");

                    b.Property<string>("CommodityCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyNameID")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultPurchaseUnit")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultSalesUnit")
                        .HasColumnType("int");

                    b.Property<double?>("InterStateRate")
                        .HasColumnType("float");

                    b.Property<string>("ItemCode")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("ItemName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ItemType")
                        .HasColumnType("int");

                    b.Property<double?>("MRP")
                        .HasColumnType("float");

                    b.Property<double?>("Margin")
                        .HasColumnType("float");

                    b.Property<double?>("MinimumLevel")
                        .HasColumnType("float");

                    b.Property<double?>("PurchaseDiscount")
                        .HasColumnType("float");

                    b.Property<double?>("PurchaseRate")
                        .HasColumnType("float");

                    b.Property<int?>("PurchaseTaxHead")
                        .HasColumnType("int");

                    b.Property<double?>("PurchaseTaxRate")
                        .HasColumnType("float");

                    b.Property<string>("Rack")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("ReorderLevel")
                        .HasColumnType("float");

                    b.Property<double?>("SalesDiscount")
                        .HasColumnType("float");

                    b.Property<decimal?>("SalesPoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double?>("SalesRate")
                        .HasColumnType("float");

                    b.Property<int?>("SalesTaxHead")
                        .HasColumnType("int");

                    b.Property<double?>("SalesTaxRate")
                        .HasColumnType("float");

                    b.Property<int?>("SizeId")
                        .HasColumnType("int");

                    b.Property<bool?>("StockType")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UserDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<double?>("WholeSaleRate")
                        .HasColumnType("float");

                    b.HasKey("ItemId");

                    b.ToTable("Item", "Reference");
                });

            modelBuilder.Entity("Inventory.Server.Models.PurchaseMaster", b =>
                {
                    b.Property<int>("PurchaseNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseNo"));

                    b.Property<double?>("AddDiscount")
                        .HasColumnType("float");

                    b.Property<string>("BENo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BatchNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BillType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CancelDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CancelFlag")
                        .HasColumnType("bit");

                    b.Property<int?>("CashVoucherID")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryType")
                        .HasColumnType("int");

                    b.Property<double?>("Cess")
                        .HasColumnType("float");

                    b.Property<double?>("Clearing")
                        .HasColumnType("float");

                    b.Property<double?>("Cooli")
                        .HasColumnType("float");

                    b.Property<double?>("CustomsDuty")
                        .HasColumnType("float");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EditFlag")
                        .HasColumnType("bit");

                    b.Property<int?>("FinancialYearID")
                        .HasColumnType("int");

                    b.Property<int?>("FormType")
                        .HasColumnType("int");

                    b.Property<double?>("Freight")
                        .HasColumnType("float");

                    b.Property<bool?>("FreightAfter")
                        .HasColumnType("bit");

                    b.Property<int?>("GodownID")
                        .HasColumnType("int");

                    b.Property<double?>("GrandTotal")
                        .HasColumnType("float");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("JournelVoucherID")
                        .HasColumnType("int");

                    b.Property<string>("LorryNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Narration")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("NetAmount")
                        .HasColumnType("float");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("int");

                    b.Property<double?>("OtherCharges")
                        .HasColumnType("float");

                    b.Property<decimal?>("OtherChargesBill")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OtherChargesExtra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PartyID")
                        .HasColumnType("int");

                    b.Property<string>("PartyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PurchaseMode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("PurchaseType")
                        .HasColumnType("int");

                    b.Property<bool>("ReturnedFlag")
                        .HasColumnType("bit");

                    b.Property<double?>("Roundoff")
                        .HasColumnType("float");

                    b.Property<double?>("TotalDiscount")
                        .HasColumnType("float");

                    b.Property<double?>("TotalExciseDuty")
                        .HasColumnType("float");

                    b.Property<double?>("TotalTax")
                        .HasColumnType("float");

                    b.Property<double?>("Totalamount")
                        .HasColumnType("float");

                    b.Property<double?>("Unloading")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UserDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<bool?>("isEstimate")
                        .HasColumnType("bit");

                    b.HasKey("PurchaseNo");

                    b.ToTable("PurchaseMaster");
                });

            modelBuilder.Entity("Inventory.Server.Models.SalesMaster", b =>
                {
                    b.Property<int>("SalesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalesID"));

                    b.Property<double?>("AddDiscount")
                        .HasColumnType("float");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Address2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("AgentId")
                        .HasColumnType("int");

                    b.Property<string>("BillType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CancelDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CancelFlag")
                        .HasColumnType("bit");

                    b.Property<double?>("CardAmount")
                        .HasColumnType("float");

                    b.Property<decimal?>("CashBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CashRecieved")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CashVoucherID")
                        .HasColumnType("int");

                    b.Property<double?>("Cess")
                        .HasColumnType("float");

                    b.Property<int?>("Counter")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EditFlag")
                        .HasColumnType("bit");

                    b.Property<int?>("FinancialYearID")
                        .HasColumnType("int");

                    b.Property<int?>("FormType")
                        .HasColumnType("int");

                    b.Property<int?>("GodownID")
                        .HasColumnType("int");

                    b.Property<double?>("GrandTotal")
                        .HasColumnType("float");

                    b.Property<int?>("ItemType")
                        .HasColumnType("int");

                    b.Property<int?>("JournelVoucherID")
                        .HasColumnType("int");

                    b.Property<string>("Narration")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Narration1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("NetAmount")
                        .HasColumnType("float");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("int");

                    b.Property<decimal?>("OtherCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OtherChargesBill")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OtherChargesExtra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PODate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PONo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PartyID")
                        .HasColumnType("int");

                    b.Property<string>("PartyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PendingAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RateType")
                        .HasColumnType("int");

                    b.Property<bool>("ReturnedFlag")
                        .HasColumnType("bit");

                    b.Property<double?>("Roundoff")
                        .HasColumnType("float");

                    b.Property<int?>("SCODE")
                        .HasColumnType("int");

                    b.Property<int>("SalesCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SalesDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SalesType")
                        .HasColumnType("int");

                    b.Property<bool?>("SalesmanGodownFlag")
                        .HasColumnType("bit");

                    b.Property<double?>("TotalDiscount")
                        .HasColumnType("float");

                    b.Property<double?>("TotalExciseDuty")
                        .HasColumnType("float");

                    b.Property<decimal?>("TotalPoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double?>("TotalTax")
                        .HasColumnType("float");

                    b.Property<double?>("Totalamount")
                        .HasColumnType("float");

                    b.Property<double?>("UPIAmount")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UserDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("VoucherId")
                        .HasColumnType("int");

                    b.Property<bool?>("isEstimate")
                        .HasColumnType("bit");

                    b.HasKey("SalesID");

                    b.ToTable("SalesMaster");
                });

            modelBuilder.Entity("Inventory.Server.Models.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<int?>("CommissionSalesNo")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Multiplier")
                        .HasColumnType("numeric(18, 3)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UnitId");

                    b.ToTable("Unit", "Reference");
                });

            modelBuilder.Entity("Inventory.Server.Models.Category", b =>
                {
                    b.HasOne("Inventory.Server.Models.CategoryGroup", "CategoryGroup")
                        .WithMany()
                        .HasForeignKey("CategoryGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryGroup");
                });

            modelBuilder.Entity("Inventory.Server.Models.Employee", b =>
                {
                    b.HasOne("Inventory.Server.Models.Core.Designation", "Designation")
                        .WithMany()
                        .HasForeignKey("DesignationId");

                    b.Navigation("Designation");
                });
#pragma warning restore 612, 618
        }
    }
}
